/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { applyProps } from '@react-three/fiber'
import { Turn } from '../types/situation'

type GLTFResult = GLTF & {
  nodes: {
    Plane002: THREE.Mesh
  }
}

// eslint-disable-next-line no-undef
export default function Mask(props: JSX.IntrinsicElements['group'] & {color: Turn}) {
  const group = useRef<THREE.Group>()
  const { nodes } = useGLTF('/Masks.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={props.color === 'red' ? new THREE.MeshStandardMaterial({ color: 0xFF0000, roughness: 0.5 }) : new THREE.MeshStandardMaterial({ color: 0x0000FF, roughness: 0.5 })}
        scale={[4, 1, 2]}
        rotation={ props.color === 'blue' ? [0, Math.PI, 0] : [0, 0, 0]}

      />
    </group>
  )
}

useGLTF.preload('/Masks.glb')
